import { Metadata } from "next";

type PropTypes = {
    children: React.ReactNode,
    notifications: React.ReactNode,
    users: React.ReactNode,
}

export const metadata: Metadata = {
    title: "AMS - Analytics",
    description: "Generated by create next app",
  };

const DashboardLayout = ({children, notifications, users}: PropTypes) => {
  return (
    <div style={{margin:40, display:'grid', gap:30}}>
    <div>{children}</div>
    <div>{notifications}</div>
    <div>{users}</div>
    </div>
    
  )
}

export default DashboardLayout